[phases.setup]
nixPkgs = [
    'python3',
    'cairo',
    'pango',
    'gdk-pixbuf',
    'libffi',
    'postgresql',
    'gdal',        # INDISPENSABLE pour PostGIS
    'geos'         # INDISPENSABLE pour la géométrie
]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
