databases:
  - name: oblink-db
    databaseName: oblink
    user: oblink_user
    plan: free

services:
  # Backend: Django Service
  - type: web
    name: oblink-backend
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: "./setup_backend.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: oblink-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: static
          name: oblink-frontend
          property: url

  # Frontend: React Static Site
  - type: static
    name: oblink-frontend
    region: frankfurt
    plan: free
    repo: https://github.com/Sergi77-Bo/oblink-v5 # Will be auto-filled by Render when using Blueprint
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: oblink-backend
          property: url
